FROM node:14-slim
WORKDIR /usr/src/app
COPY ./package.json ./
RUN npm install
COPY . .

ARG BASE_URL
ENV REACT_APP_BASE_URL=${BASE_URL}

RUN npm run build

##second stage
FROM caddy:2.1.1-alpine
ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

EXPOSE 80
EXPOSE 443